package net.vulkanmod.astc;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.fabricmc.fabric.api.resource.SimpleSynchronousResourceReloadListener;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.ResourceManager;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

/**
 * Fabric resource reload listener.
 *
 * On every resource reload:
 *   1. Clears the ASTC registry.
 *   2. Re-detects Vulkan ASTC capabilities (device may now be ready).
 *   3. Reads astc_index.json (generated by Gradle convertASTCTextures task).
 *   4. Loads bundled ASTC bytes into {@link ASTCTextureRegistry}.
 *   5. Warm-starts disk cache lookups for any third-party mod textures.
 *
 * Resource layout inside the JAR:
 *   assets/nexusastcpack/astc_index.json         ← index of all bundled textures
 *   assets/minecraft/textures/block/stone.astc   ← pre-converted vanilla textures
 */
public class ASTCResourceProvider implements SimpleSynchronousResourceReloadListener {

    private static final Gson GSON = new Gson();
    private static final ResourceLocation ID =
            ResourceLocation.fromNamespaceAndPath("nexusastcpack", "astc_loader");
    private static final String INDEX_PATH = "/assets/nexusastcpack/astc_index.json";

    @Override
    public ResourceLocation getFabricId() { return ID; }

    @Override
    public void onResourceManagerReload(ResourceManager manager) {
        ASTCTextureRegistry.clear();

        // Re-detect ASTC support — Vulkan device is definitely initialised by now
        ASTCCapabilities.redetect();

        if (!ASTCCapabilities.isLdrSupported()) {
            NexusASTCPack.LOGGER.info("[NexusASTCPack] ASTC not supported — serving PNG normally");
            return;
        }

        loadBundledTextures();
        NexusASTCPack.LOGGER.info("[NexusASTCPack] Resource reload complete — {} ASTC textures registered",
                ASTCTextureRegistry.size());
    }

    private void loadBundledTextures() {
        try (InputStream indexStream =
                ASTCResourceProvider.class.getResourceAsStream(INDEX_PATH)) {

            if (indexStream == null) {
                NexusASTCPack.LOGGER.warn(
                    "[NexusASTCPack] astc_index.json not found in JAR — " +
                    "run './gradlew convertASTCTextures' with ASTCENC_PATH set to generate bundled textures");
                return;
            }

            JsonObject root = GSON.fromJson(
                    new InputStreamReader(indexStream, StandardCharsets.UTF_8), JsonObject.class);
            JsonArray entries = root.getAsJsonArray("entries");
            if (entries == null || entries.isEmpty()) {
                NexusASTCPack.LOGGER.info("[NexusASTCPack] astc_index.json is empty — no bundled textures");
                return;
            }

            int loaded = 0, missing = 0;
            for (var el : entries) {
                JsonObject e = el.getAsJsonObject();
                String tex  = e.get("texture").getAsString();   // "minecraft:textures/block/stone"
                int vkFmt   = e.get("vkFormat").getAsInt();
                int bx      = e.get("blockSizeX").getAsInt();
                int by      = e.get("blockSizeY").getAsInt();

                String[] parts = tex.split(":", 2);
                if (parts.length != 2) continue;

                // JAR resource: /assets/<namespace>/<path>.astc
                String jarPath = "/assets/" + parts[0] + "/" + parts[1] + ".astc";

                try (InputStream astcStream =
                        ASTCResourceProvider.class.getResourceAsStream(jarPath)) {
                    if (astcStream == null) { missing++; continue; }

                    byte[] data = astcStream.readAllBytes();
                    ResourceLocation loc = ResourceLocation.fromNamespaceAndPath(parts[0], parts[1]);
                    ASTCTextureRegistry.put(loc, new ASTCTextureRegistry.ASTCEntry(data, vkFmt, bx, by));
                    loaded++;
                }
            }

            if (missing > 0)
                NexusASTCPack.LOGGER.warn("[NexusASTCPack] {} entries in index but .astc file missing from JAR", missing);
            NexusASTCPack.LOGGER.info("[NexusASTCPack] Loaded {}/{} bundled ASTC textures",
                    loaded, entries.size());

        } catch (Exception e) {
            NexusASTCPack.LOGGER.error("[NexusASTCPack] Failed to load bundled textures: {}", e.getMessage());
        }
    }
}
